name: mobile_kit_demo
description: "A new Flutter mobile kit demo project powered by SSA Group."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  # 0.0.1
  mobile_kit:
    path: ../mobile_kit
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
